### ISSUE TITLE
Doc for keystroke values

### ISSUE THREAD

**Issue by TechnologyClassroom** [ES-factory/ES-Timer#6]
I tried ES-Timer on a Linux based system.  The flash seemed to work.  The lights seem to match, but the keystroke did not lock.  My issue might have to do with my [udev rules](http://digistump.com/wiki/digispark/tutorials/linuxtroubleshooting).

Can you explain these values found in [./lib/ESTimer.zip ESTimer/ESTimer.h](https://github.com/ES-factory/ES-Timer/blob/master/lib/ESTimer.zip)?

```
#if SYSTEM_OS == WINDOWS
#   define LOCK_SHORTCUT 0x08, 0x0F
#elif SYSTEM_OS == LINUX
#   define LOCK_SHORTCUT 0x01 | 0x04, 0x0F
#else
#   define LOCK_SHORTCUT 0x01 | 0x08, 0x14
#endif
```

I assume it correlates to these values:

* 0x08 = Windows or super key
* 0x0F = l
* 0x01 = Control
* 0x04 = Alt
* 0x14 = q

I read [hut1_3_0.pdf](https://usb.org/sites/default/files/hut1_3_0.pdf) pages 88-94 and [hid1_11.pdf](https://www.usb.org/sites/default/files/documents/hid1_11.pdf) pages 59 and 60, but I am still having trouble understanding the Super, Control, and Alt portion.  What differentiates between 0x08 being a modifier and being the letter e?

**Comment by ErfanSn** [comment]
If you refer to page 56 of [hi1_11](https://www.usb.org/sites/default/files/documents/hid1_11.pdf) and read it carefully, you will definitely notice the difference. In fact, the value in the first part before the **comma** is a modifier and the position of the 1 bits in the value is important, not the value itself. As a result, if **0x08**  convert to binary, it is equal to **0b00001000** and according to the document, the fourth position bit indicates the use of GUI key or windows key.

Because I use the Windows operating system, unfortunately, I have not had the opportunity to test it on the Linux and macOS operating systems, and I have only searched the Internet for shortcuts. If the shortcut is not correct, you can send it to me so that I can correct it.  In addition, you can share your ES timer image in the discussions section.

**Comment by TechnologyClassroom** [comment]
Thank you!  That explanation helps.  I'll report back once I have it working.
